### ISSUE TITLE
Use CSS modules

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/react-gallery#12]
Not sure why this isn't the default

**Comment by andrewrubin** [comment]
I think this was a mis-informed decision on my part when initially creating this package. I was under the impression that CSS Modules were a runtime dependency, and thus needed to be included on every project, regardless of whether the project uses CSS Modules. If this is not the case, let's update!

**Comment by marlonmarcello** [comment]
With the new Vite setup it will take care of bundling for us.  
The consuming apps will still import the styles like they do now but we'll get scoped styles!
